kindeffects/kindeffects/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage/', views.update, name='update'),
    path('mypage/delete', views.delete, name='delete'),
]

kindeffects/kindeffects/kindeffects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('maps/', include('maps.urls')),
    path('stores/', include('stores.urls')),
]

kindeffects/kindeffects/maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
]

kindeffects/kindeffects/stores/urls.py
from django.urls import path
from . import views

app_name = 'stores'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.store_new, name='store_new'),
    path('update/', views.update, name='update'),
    path('<int:store_pk>', views.detail, name='detail'),
    # QR 코드가 인식됨
    path('visiting/<int:store_pk>', views.visiting, name='visiting'),
    # 업체의 MyPage
    path('<int:store_pk>/mypage', views.mypage, name='mypage'),
    
    # 후원현황
    path('report/', views.report, name='report')
]

kindeffects/kindeffects/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from stores.models import Store

class User(AbstractUser):
    phone = models.CharField(max_length=20)
    name_kr = models.CharField(max_length=10)
    store_regist = models.CharField(max_length=100)
    # store = models.ForeignKey(Store, on_delete=models.CASCADE, blank=True, null=True)
    store = models.OneToOneField(Store, on_delete=models.CASCADE, blank=True, null=True)

kindeffects/kindeffects/accounts/forms.py
from django import forms
# from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('name_kr', 'phone', 'store_regist', )


class CustomUserCreationForm(UserCreationForm):
    phone = forms.CharField(
        label='핸드폰 번호',
        widget=forms.TextInput(
            attrs={
                'type':'tel',
            }
        )
    )
    username = forms.CharField(
        label='아이디',
        help_text='문자, 숫자 그리고 @/./+/-/_만 가능합니다.'
    )
    name_kr = forms.CharField(
        label='사업자 이름'
    )
    store_regist = forms.CharField(
        label='사업자 등록번호'
    )

    class Meta():
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'name_kr', 'phone', 'store_regist', 'store')
        # fields = '__all__'

kindeffects/kindeffects/accounts/views.py
from django.shortcuts import render,redirect
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
@require_http_methods(['GET','POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('maps:index')
        
    if request.method=='POST':
        form = CustomUserCreationForm(request.POST)
        # print(request.POST)
        # print(form.is_valid())
        # print(form.error_messages)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('maps:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('maps:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('maps:index')

    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['POST',])
def logout(request):
    auth_logout(request)
    return redirect('maps:index')


@login_required
def update(request):
    # form = CustomUserChangeForm(instance = request.user)
    user = User.objects.get(username=request.user)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        print(form.data)
        print(form.errors)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return redirect('accounts:update')
    else:
	    form = CustomUserChangeForm(instance=user)

    context = {
        'form': form,
    }
    return render(request, 'accounts/mypage.html', context)


@login_required
def delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('maps:index')
    return redirect('accounts:mypage')

kindeffects/kindeffects/accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    
  <!-- ***** Breadcrumb Area Start ***** -->
    <div class="breadcumb-area">
        <div class="container h-100">
            <div class="row h-100 align-items-end">
                <div class="col-12">
                <div class="breadcumb--con">
                    <h2 class="title">MyPage</h2>
                    <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                        <li class="breadcrumb-item"><a href="#">MyPage</a></li>
                        <li class="breadcrumb-item active" aria-current="page">MyPage</li>
                    </ol>
                    </nav>
                </div>
                </div>
            </div>
        </div>
    </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Contact Area Start ***** -->
    <section class="mona-contact-area section-padding-80-0">
        <div class="container">
            <div class="row align-items-center justify-content-between">        
                <div class="col-12 col-lg-6 col-xl-6">
                    <div class="mona-contact-form mb-80">

                        <div class="contact-heading">
                            <h2>회원정보</h2>
                        </div>

                        <form action="{% url 'accounts:update' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name_kr">이름 </label>
                                <input type="text" class="form-control" name="name_kr" value="{{ user.name_kr }}">
                            </div>
                            <div class="form-group">
                                <label for="phone">핸드폰 번호</label>
                                <input type="text" class="form-control" name="phone" value="{{ user.phone }}">
                            </div>
                            <div class="form-group">
                                <label for="store_regist">사업자 번호</label>
                                <input type="text" class="form-control" name="store_regist" value="{{ user.store_regist }}">
                            </div>
                            <button class="btn mona-btn btn-2 mt-15">Edit</button>
                        </form>
                    </div>
                </div>
                <!-- Contact Form -->
                <div class="col-12 col-lg-6 col-xl-6">
                    <div class="mona-contact-form mb-80">
                        <div class="contact-heading">
                            <h2>가게 정보</h2>
                        </div>
                        <form action="{% url 'stores:update' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">상호명</label>
                                <input type="text" class="form-control" name="name" value="{{ user.store.name }}">
                            </div>
                            <div class="form-group">
                                <label for="num">가게 번호</label>
                                <input type="text" class="form-control" name="num" value="{{ user.store.num }}">
                            </div>
                            <div class="form-group">
                                <label for="addr">가게 주소</label>
                                <input type="text" class="form-control" name="addr" value="{{ user.store.addr }}">
                            </div>
                            <div class="form-group">
                                <label for="hour">영업 시간</label>
                                <label>시작 </label><input type="time" class="form-control" name="open_hour" value="{{ user.store.open_hour|date:"H:i" }}">
                                <br>
                                <label>종료 </label><input type="time" class="form-control" name="closed_hour" value="{{ user.store.closed_hour|date:"H:i" }}">
                            </div>
                            <div class="form-group">
                                <label for="service">제공 서비스</label>
                                <input type="text" class="form-control" name="service" value="{{ user.store.service }}">
                            </div>
                            <button class="btn mona-btn btn-2 mt-15">Edit</button>
                        </form>
                    </div>
                </div>
                <div class="userDelete" data-toggle="modal" data-target="#UserDeleteModal">
                    <p class="btn mona-btn btn-2 mt-15">계정 탈퇴</p>
                </div>
            </div>
        </div>
    </section>
  <!-- ***** Contact Area End ***** -->

{% endblock %}

kindeffects/kindeffects/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <!-- ***** Top Search Area Start ***** -->
    <div class="top-search-area">
      <!-- Search Modal -->
      <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <!-- Close Button -->
              <button type="button" class="btn close-btn" data-dismiss="modal"><i class="fa fa-times"></i></button>
              <!-- Form -->
              <form action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                <input type="text" name="username" class="form-control" placeholder="아이디">
                <input type="password" name="password" class="form-control" placeholder="비밀번호">
                <button type="submit">SingIn</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ***** Top Search Area End ***** -->
  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area">
    <div class="container h-100">
      <div class="row h-100 align-items-end">
        <div class="col-12">
          <div class="breadcumb--con">
            <h2 class="title">Signup</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Signup</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Casting Form Area Start ***** -->
  <section class="mona-casting-form-area section-padding-80-0">
    <div class="container">
          <div class="casting-form mona-contact-form mb-80 container">
            <div class="contact-heading">
              <h3>여기에 뭐가 들어오지</h3>
              <p>여기에 뭐가 들어오면 좋을까</p>
            </div>

            <form action="{% url 'accounts:signup' %}" method="post" class="d-inline">
              {% csrf_token %}
              {% bootstrap_form form %}
              {% comment %} {{ form.as_table }} {% endcomment %}
              {% comment %} {% for field in form %}
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
              {% endfor %} {% endcomment %}
              {% comment %} <div>
                {{ form.errors }}
              </div>
              <div>
                {{ form.username.label_tag }}
                {{ form.username }}
                {{ form.username.help_text }}
              </div>
              <div>
                {{ form.password1.label_tag }}
                {{ form.password1 }}
                {{ form.password1.help_text }}                
              </div>
              <div>
                {{ form.password2.label_tag }}
                {{ form.password2 }}
                {{ form.password2.help_text }}
              </div>
              <div>
                {{ form.phone.label_tag }}
                {{ form.phone }}
              </div>
              <div>
                {{ form.name_kr.label_tag }}
                {{ form.name_kr }}
              </div>
              <div>
                {{ form.store_regist.label_tag }}
                {{ form.store_regist }}
              </div>
              <div>
                {{ form.store.label_tag }}
                {{ form.store }}
              </div> {% endcomment %}
              <button class="btn mona-btn btn-2 mt-15">SignUp</button>
            </form>
          </div>
    </div>
  </section>
  <!-- ***** Casting Form Area End ***** -->

  <!-- ***** Our Judges Area Start ***** -->
  <section class="mona-team-area">
    <div class="container">
      <div class="row">
        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>함께하고 있는 기업들</h2>
          </div>
        </div>
      </div>

      <div class="row container text-center">
        <!-- Single Judges Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-team-member-area mb-80">
            <div class="team-member-thumbnail">
              <!-- Thumbnail -->
              <img src="{% static './img/bg-img/organicJane.jpg' %}" alt="">

              <!-- Share Info -->
              <div class="share-info">
                <!-- Share Icon -->
                <div class="share-icon">
                  <a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
                </div>
                <!-- Others Icon -->
                <div class="others-icon">
                  <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                </div>
              </div>
            </div>
            <div class="team-member-info">
              <h4>Organic Jane</h4>
              <h6>choreographer</h6>
            </div>
          </div>
        </div>

        <!-- Single Judges Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-team-member-area mb-80">
            <div class="team-member-thumbnail">
              <!-- Thumbnail -->
              <img src="{% static './img/bg-img/genesis.jpg' %}" >

              <!-- Share Info -->
              <div class="share-info">
                <!-- Share Icon -->
                <div class="share-icon">
                  <a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
                </div>
                <!-- Others Icon -->
                <div class="others-icon">
                  <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                </div>
              </div>
            </div>
            <div class="team-member-info">
              <h4>Genesis BBQ</h4>
              <h6>Model</h6>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>
  <!-- ***** Our Judges Area End ***** -->


{% endblock %}