kindeffects/kindeffects/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage/', views.update, name='update'),
    path('mypage/delete', views.delete, name='delete'),
]

kindeffects/kindeffects/kindeffects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('maps/', include('maps.urls')),
    path('stores/', include('stores.urls')),
]

kindeffects/kindeffects/maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
]

kindeffects/kindeffects/stores/urls.py
from django.urls import path
from . import views

app_name = 'stores'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.store_new, name='store_new'),
    path('update/', views.update, name='update'),
    path('<int:store_pk>', views.detail, name='detail'),
    # QR 코드가 인식됨
    path('visiting/<int:store_pk>', views.visiting, name='visiting'),
    # 업체의 MyPage
    path('<int:store_pk>/mypage', views.mypage, name='mypage'),
    
    # 후원현황
    path('report/', views.report, name='report')
]

kindeffects/kindeffects/kindeffects/templates/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="선한 영향력">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>선한 영향력</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static './img/core-img/favicon.ico' %}">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/a43482d4c5.js" crossorigin="anonymous"></script>

    <!-- Kakao Map API -->
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=12b33cfeae96129823a440f07c7b2d91"></script>
    
    <style>
       /* AMCHART */
      .chartdiv {
      width: 100%;
      height: 500px;
      }

      tspan {
        font-size: large;
      }
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
    <header class="header-area">
        {% block header %}
            {% include 'nav.html' %}
        {% endblock %}
    </header>
    <!-- ***** SignIn & SignOut Area Start ***** -->
      <div class="top-search-area">
        <!-- SingIn Modal -->
        <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <!-- Close Button -->
                <button type="button" class="btn close-btn" data-dismiss="modal"><i class="fa fa-times"></i></button>
                <!-- Form -->
                <form action="{% url 'accounts:login' %}" method="post">
                  {% csrf_token %}
                  <input type="text" name="username" class="form-control" placeholder="아이디">
                  <input type="password" name="password" class="form-control" placeholder="비밀번호">
                  <button type="submit">SignIn</button>
                  <a class="btn" href="{% url 'accounts:signup' %}">SignUp</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="top-search-area">
        <!-- SignOut Modal -->
        <div class="modal fade" id="signOutModal" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <!-- Close Button -->
                <button type="button" class="btn close-btn" data-dismiss="modal"><i class="fa fa-times"></i></button>
                <!-- Form -->
                <form action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <h4>로그아웃 하시겠습니까?</h4>
                  <button type="submit">SignOut</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- ***** SignIn & SignOut Area End ***** -->
    <!-- ***** User Delete Start ***** -->
      <div class="top-search-area">
        <!-- SignOut Modal -->
        <div class="modal fade" id="UserDeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <!-- Close Button -->
                <button type="button" class="btn close-btn" data-dismiss="modal"><i class="fa fa-times"></i></button>
                <!-- Form -->
                <form action="{% url 'accounts:delete' %}" method="post">
                  {% csrf_token %}
                  <p>정말로 회원을 탈퇴하시겠습니까?</p>
                  <button type="submit">탈퇴</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- ***** User Delete End ***** -->
    <div class="container">
        {% block content %}
        {% endblock  %}
    </div>
        {% block footer %}
            {% include 'footer.html' %}
        {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    

    <!-- ******* All JS ******* -->
    <!-- jQuery js -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- All js -->
    <script src="{% static 'js/mona.bundle.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/default-assets/active.js' %}"></script>

</body>
</html>

kindeffects/kindeffects/kindeffects/templates/footer.html
{% load static %}

  <!-- ***** Footer Area Start ***** -->
  <footer class="footer-area section-padding-80-0">
    <div class="container">
      <div class="row justify-content-between">

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
          <div class="single-footer-widget mb-60">
            <!-- Logo -->
            <a href="#" class="d-block mb-4"><img src="" alt=""></a>
            <p>Integer vehicula mauris libero, at molestie eros imperdiet sit amet. Suspendisse mattis ante sit amet ante.</p>
            <div class="copywrite-text">
              <p>&copy; 
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
          <div class="single-footer-widget mb-60">
            <!-- Widget Title -->
            <h4 class="widget-title">Our Link</h4>

            <!-- Catagories Nav -->
            <nav>
              <ul class="our-link">
                <li><a href="#">New Faces</a></li>
                <li><a href="#">Model Of the Week</a></li>
                <li><a href="#">Classic Women</a></li>
                <li><a href="#">Privacy Terms</a></li>
                <li><a href="#">Classic Men</a></li>
                <li><a href="#">Conditions</a></li>
                <li><a href="#">Hair & Styles</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </nav>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-lg-4 col-xl-3">
          <div class="single-footer-widget mb-60">
            <!-- Widget Title -->
            <h4 class="widget-title">Contact</h4>
            <!-- Footer Content -->
            <div class="footer-content mb-30">
              <h4>+01-3-8888-6868</h4>
              <h6>40 Baria Sreet 133/2 NewYork City</h6>
            </div>
            <!-- Social Info -->
            <div class="footer-social-info">
              <a href="#" class="facebook" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="twitter" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="pinterest" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
              <a href="#" class="instagram" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="youtube" data-toggle="tooltip" data-placement="top" title="YouTube"><i class="fa fa-youtube-play"></i></a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </footer>
  <!-- ***** Footer Area End ***** -->

kindeffects/kindeffects/kindeffects/templates/nav.html
{% load static %}
    <!-- Main Header Start -->
    <div class="main-header-area">
      <div class="classy-nav-container breakpoint-off">
        <!-- Classy Menu -->
        <nav class="classy-navbar justify-content-between" id="monaNav">

          <!-- Background Curve -->
          <div class="bg-curve" style="background-image: url({% static '/img/core-img/curve.png' %});"></div>

          <!-- Logo -->
          <a class="nav-brand" href="index.html"><img src="{% static '/img/core-img/logo.png' %}" alt="" style="width:60px;"></a>

          <!-- Navbar Toggler -->
          <div class="classy-navbar-toggler">
            <span class="navbarToggler"><span></span><span></span><span></span></span>
          </div>

          <!-- Menu -->
          <div class="classy-menu">
            <!-- Menu Close Button -->
            <div class="classycloseIcon">
              <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
            </div>

            <!-- Nav Start -->
            <div class="classynav">
              <ul id="nav">
                <li class="current-item"><i class="fas fa-sign-in-alt"></i></li>
                <li class="current-item"><a href="{% url 'maps:index' %}">Home</a></li>
                {% comment %} <li><a href="{% url 'maps:about' %}">About Us</a></li> {% endcomment %}
                <li><a href="{% url 'stores:index' %}">Stores</a></li>
                {% if user.is_authenticated %} 
                  <li><a href="#">Mypage</a>
                    <ul class="dropdown">
                      <li><a href="{% url 'accounts:update' %}">- MyPage</a></li>
                      <li><a href="#">- QR생성</a></li>
                    </ul> 
                  </li>
                {% endif %}
              </ul>

              <!-- Search Icon -->
              {% comment %} <div class="search-icon" data-toggle="modal" data-target="#searchModal">
                <i class="icon_search"></i>
              </div> {% endcomment %}
              
              {% if user.is_authenticated %}  
                <div class="search-icon logout" data-toggle="modal" data-target="#signOutModal">
                  <i class="fas fa-sign-out-alt"></i>
                </div>
              {% else %}
                <div class="search-icon sign-in" data-toggle="modal" data-target="#signInModal">
                  <i class="fas fa-sign-in-alt"></i>
                </div>
              {% endif %}
            </div>
            <!-- Nav End -->

          </div>
        </nav>
      </div>
    </div>
    