kindeffects/kindeffects/kindeffects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('maps/', include('maps.urls')),
    path('stores/', include('stores.urls')),
]

kindeffects/kindeffects/maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
]

kindeffects/kindeffects/stores/urls.py
from django.urls import path
from . import views

app_name = 'stores'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.store_new, name='store_new'),
    path('update/', views.update, name='update'),
    path('<int:store_pk>', views.detail, name='detail'),
    # QR 코드가 인식됨
    path('visiting/<int:store_pk>', views.visiting, name='visiting'),
    # 업체의 MyPage
    path('<int:store_pk>/mypage', views.mypage, name='mypage'),
    
    # 후원현황
    path('report/', views.report, name='report')
]

kindeffects/kindeffects/stores/models.py
from django.db import models
from imagekit.models import ProcessedImageField

# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=100)
    num = models.CharField(max_length=100)
    addr = models.CharField(max_length=500)
    open_hour = models.TimeField()
    closed_hour = models.TimeField()
    service = models.TextField()    

    def __str__(self):
        return self.name


class Visiting(models.Model):
    visiting_time = models.DateTimeField(auto_now=True)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, blank=True, null=True)

kindeffects/kindeffects/stores/forms.py
from django import forms
from .models import Store

class StoreForm(forms.ModelForm):
    open_hour = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type':'time',
            }
        )
    )
    closed_hour = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type':'time',
            }
        )
    )
    num = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type':'tel',
            }
        )
    )
    class Meta:
        model = Store
        fields = '__all__'

kindeffects/kindeffects/stores/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Store, Visiting
from .forms import StoreForm
from django.contrib.auth.decorators import login_required

import qrcode
import qrcode.image.svg
# Create your views here.
def index(request):
    stores = Store.objects.all()
    context = {
        'stores' : stores,
    }
    return render(request, 'stores/index.html', context)


def store_new(request):
    if request.method == 'POST':
        form = StoreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('stores:index')
    else:
        form = StoreForm()

    context = {
        'form': form,
    }
    return render(request, 'stores/store_new.html', context)

@login_required
def update(request):
    print(request.user.store_id)
    store = Store.objects.get(pk=request.user.store_id)
    if request.method == 'POST':
        form = StoreForm(request.POST, instance=store)
        if form.is_valid():
            form.save()
    return redirect('accounts:update')




def detail(request, store_pk):
    store = get_object_or_404(Store, pk=store_pk)
    context = {
        'store': store,
    }
    return render(request, 'stores/store_detail.html', context)

# qr이 인식되면 visit_time이 저장됨.
def visiting(request, store_pk):
    store = get_object_or_404(Store, pk=store_pk)
    visiting = Visiting.objects.create()
    visiting.store = store
    visiting.save()
    return redirect('stores:detail', store_pk)

# 로그인 조건이 추가되었음
@login_required
def mypage(request, store_pk):
    store = get_object_or_404(Store, pk=store_pk)

    # 수퍼유저로 로그인 했을 때 또는
    # 로그인한 사용자의 업체일 때만 --- 접근가능
    if request.user.is_superuser or request.user.store == store:
        domain = "http://www.dreamtree.site"
        store_url = f"{domain}/stores/visiting/{store_pk}/" 
        visitings = Visiting.objects.filter(store_id=store_pk)
        visiting_dates = [visiting.visiting_time.date() for visiting in visitings]
        visiting_dates = set(visiting_dates)
        visiting_dates = sorted(visiting_dates)
        
        # 방문횟수 DB를 dictionary로 만들어 context로 전달
        visitings_date_cnt ={}
        for date in visiting_dates:
            visiting_list = [visiting for visiting in visitings if visiting.visiting_time.date() == date]
            cnt = len(visiting_list)
            visitings_date_cnt[date] = cnt            
    
        context = {
            'store': store,
            'store_url': store_url,
            # 'total_visiting_date_cnt': total_visiting_date_cnt,
            'visitings_date_cnt': visitings_date_cnt,
        }
        return render(request, 'stores/store_mypage.html', context)

    # 로그인을 했으나, 다른 업체일 때 -- 본인 업체 Mypage로 이동
    return redirect('maps:index')

# 서포트 현황 report 페이지 보기
def report(request):
    all_cnt = Visiting.objects.count()
    print("all_cnt::::", all_cnt)

    # 날짜 데이터 모아오기
    visitings = Visiting.objects.all()
    visiting_dates = [visiting.visiting_time.date() for visiting in visitings]
    visiting_dates = set(visiting_dates)
    visiting_dates = sorted(visiting_dates)

    visitings_date_cnt ={}
    for date in visiting_dates:
        visiting_list = [visiting for visiting in visitings if visiting.visiting_time.date() == date]
        cnt = len(visiting_list)
        visitings_date_cnt[date] = cnt

    context = {
        'all_cnt': all_cnt,
        'visitings_date_cnt': visitings_date_cnt,
    }

    return render(request, 'stores/report.html', context)

kindeffects/kindeffects/stores/templates/stores/column_graph.html
{% load static %}

<!-- Resources -->
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

<!-- Chart code -->
<script>
    am4core.ready(function() {

    // Themes begin
    am4core.useTheme(am4themes_animated);
    // Themes end

    /**
    * Chart design taken from Samsung health app
    */

    var chart = am4core.create("column_graph", am4charts.XYChart);
    chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

    chart.paddingBottom = 30;

    chart.data = [{
        "name": "누적 이용자",
        "steps": {{ all_cnt }},
        "href": "{% static 'img/core-img/logo.png' %}"
    }];

    var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
    categoryAxis.dataFields.category = "name";
    categoryAxis.renderer.grid.template.strokeOpacity = 0;
    categoryAxis.renderer.minGridDistance = 10;
    categoryAxis.renderer.labels.template.dy = 35;
    categoryAxis.renderer.tooltip.dy = 35;

    var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.renderer.inside = true;
    valueAxis.renderer.labels.template.fillOpacity = 0.3;
    valueAxis.renderer.grid.template.strokeOpacity = 0;
    valueAxis.min = 0;
    valueAxis.cursorTooltipEnabled = false;
    valueAxis.renderer.baseGrid.strokeOpacity = 0;

    var series = chart.series.push(new am4charts.ColumnSeries);
    series.dataFields.valueY = "steps";
    series.dataFields.categoryX = "name";
    series.tooltipText = "{valueY.value}";
    series.tooltip.pointerOrientation = "vertical";
    series.tooltip.dy = - 6;
    series.columnsContainer.zIndex = 10;

    var columnTemplate = series.columns.template;
    columnTemplate.width = am4core.percent(50);
    columnTemplate.maxWidth = 66; //그래프 기둥 두께
    columnTemplate.column.cornerRadius(60, 60, 10, 10);
    columnTemplate.strokeOpacity = 0;

    series.heatRules.push({ target: columnTemplate, property: "fill", dataField: "valueY", min: am4core.color("#e5dc36"), max: am4core.color("#5faa46") });
    series.mainContainer.mask = undefined;

    var cursor = new am4charts.XYCursor();
    chart.cursor = cursor;
    cursor.lineX.disabled = true;
    cursor.lineY.disabled = true;
    cursor.behavior = "none";

    var bullet = columnTemplate.createChild(am4charts.CircleBullet);
    bullet.circle.radius = 50; // 불렛 동그라미 크기
    bullet.valign = "bottom";
    bullet.align = "center";
    bullet.isMeasured = true;
    bullet.mouseEnabled = false;
    bullet.verticalCenter = "bottom";
    bullet.interactionsEnabled = false;

    var hoverState = bullet.states.create("hover");
    var outlineCircle = bullet.createChild(am4core.Circle);
    outlineCircle.adapter.add("radius", function (radius, target) {
        var circleBullet = target.parent;
        return circleBullet.circle.pixelRadius + 15; //불렛그림 테두리 두께
    })

    var image = bullet.createChild(am4core.Image);
    image.width = 130; // 불렛그림 내부 크기
    image.height = 130;  // 불렛그림 내부 크기
    image.horizontalCenter = "middle";
    image.verticalCenter = "middle";
    image.propertyFields.href = "href";

    image.adapter.add("mask", function (mask, target) {
        var circleBullet = target.parent;
        return circleBullet.circle;
    })

    var previousBullet;
    chart.cursor.events.on("cursorpositionchanged", function (event) {
        var dataItem = series.tooltipDataItem;

        if (dataItem.column) {
            var bullet = dataItem.column.children.getIndex(1);

            if (previousBullet && previousBullet != bullet) {
                previousBullet.isHover = false;
            }

            if (previousBullet != bullet) {

                var hs = bullet.states.getKey("hover");
                hs.properties.dy = -bullet.parent.pixelHeight + 30;
                bullet.isHover = true;

                previousBullet = bullet;
            }
        }
    })

    }); // end am4core.ready()
</script>

<!-- HTML -->
<div class="chartdiv" id="column_graph"></div>

kindeffects/kindeffects/stores/templates/stores/graph.html
<script src="https://d3js.org/d3.v5.min.js"></script>
<div class="chart"></div>
    <script>
      var data = [10, 20, 30, 40, 50];

      d3.select(".chart").selectAll("div").data(data)
        .enter().append("div")
        .style("width", function(d) { return d*10 + "px"; })
        .text(function(d) { return d; });
    </script>   

kindeffects/kindeffects/stores/templates/stores/index.html
{% extends 'base.html' %}

{% block style %}
    /* 가로막대 차트 */
    /*
    .chart div {
      font: 10px sans-serif;
      background-color: steelblue;
      text-align: right;
      padding: 3px;
      margin: 1px;
      color: white;
    }
    */

   

    
{% endblock  %}

{% block content %}
    <h1 class="text-center">store list</h1>
    <a href="{% url 'stores:store_new' %}" class="btn btn-primary">정보작성</a>
    <hr>
    <table>
        <thead>
           <td>name</td> 
           <td>num</td> 
           <td>addr</td> 
           <td>open_hour</td> 
           <td>closed_hour</td> 
           <td>service</td> 
           <td>방문횟수</td>            
                       
        </thead>
        {% for store in stores %}
            <tr>
                <td>{{ store.name }}</td>
                <td>{{ store.num }}</td>
                <td>{{ store.addr }}</td>
                <td>{{ store.open_hour }}</td>
                <td>{{ store.closed_hour }}</td>
                <td>{{ store.service }}</td>
                <td>{{ store.visiting_set.count }}</td>
                
            </tr>
        {% endfor %}
    </table>

<!-- 그래프 삽입 -->



<div class="d-flex bd-highlight">
  <div class="p-2 flex-grow-1 bd-highlight">{% include 'stores/line_graph.html' %}</div>
  <div class="p-2 bd-highlight">{% include 'stores/column_graph.html' %}</div>
</div>

<!-- 그래프 삽입 끝-->
 
{% endblock %}

kindeffects/kindeffects/stores/templates/stores/line_graph.html
{% load static %}

<!-- Resources -->
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

<!-- Chart code -->
<script>
  am4core.ready(function() {

      // Themes begin
      am4core.useTheme(am4themes_animated);
      // Themes end

      // Create chart instance
      var chart = am4core.create("line_graph", am4charts.XYChart);

      // Add data
      chart.data = [
      {% for key, value in visitings_date_cnt.items %}
      {
        "date": new Date({{ key.year }}, {{ key.month|add:"-1" }}, {{ key.day }}),
        "value": {{ value }}
      },
      {% endfor %}
      ]


      // Create axes
      var dateAxis = chart.xAxes.push(new am4charts.DateAxis());

      // Create value axis
      var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
      valueAxis.min = 0; // 세로축 최소값
      valueAxis.max = 10; // 가로축 최대값 (생략하면 최적화됨)

      // Create series
      var lineSeries = chart.series.push(new am4charts.LineSeries());
      lineSeries.dataFields.valueY = "value";
      lineSeries.dataFields.dateX = "date";
      lineSeries.name = "Sales";
      lineSeries.strokeWidth = 3;

      // Add simple bullet
      var bullet = lineSeries.bullets.push(new am4charts.Bullet());
      var image = bullet.createChild(am4core.Image);
      // image.href = "https://www.amcharts.com/lib/images/star.svg";
      image.href = "{% static 'img/core-img/healthy-food.svg' %}"
      image.width = 30;
      image.height = 30;
      image.horizontalCenter = "middle";
      image.verticalCenter = "middle";

  }); // end am4core.ready()
</script>

<!-- HTML -->
<div class="chartdiv" id="line_graph"></div>

kindeffects/kindeffects/stores/templates/stores/report.html
{% extends 'base.html' %}

{% block content %}

  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area">
    <div class="container h-100">
      <div class="row h-100 align-items-end">
        <div class="col-12">
          <div class="breadcumb--con">
            <h2 class="title">참여현황 리포트</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Casting</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Client Feedback Area Start ***** -->
  <section class="clients-feedback-area section-padding-0-80 clearfix">
    <div class="container">
      <div class="row">
        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>총 {{ all_cnt }} 번 누적방문</h2>
          </div>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-12 col-md-10">
          <div class="slider slider-for">

            <!-- Client Feedback Text -->
            <div class="client-feedback-text text-center">
              <div class="quote-icon">
                <i class="icon_quotations" aria-hidden="true"></i>
              </div>
              <div class="client-description text-center">
                <h4>“선한프로젝트 참여 업체에 방문해 주세요. 당신이 비운 한 그릇이 아이들을 후원하는 업체에게 큰 힘이 됩니다.”</h4>
              </div>
            </div>           
          </div>
        </div>        
      </div>
    </div>
  </section>
  <!-- ***** Client Feedback Area End ***** -->

  <!-- ***** Casting Form Area Start ***** -->
  <section class="mona-casting-form-area section-padding-80-0">
    <div class="container">
      <div class="row align-items-center justify-content-between">

        <!-- 그래프 시작-->

            <div class='col-md-8'>{% include 'stores/line_graph.html' %}</div>
            <div class='col-md-4'>{% include 'stores/column_graph.html' %}</div>

        <!-- 그래프 종료-->

      </div>
    </div>
  </section>
  <!-- ***** Casting Form Area End ***** -->

{% endblock  %}

kindeffects/kindeffects/stores/templates/stores/store_detail.html
{% extends 'base.html' %} 

{% load static %}

{% block content %}

  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area">
    <div class="container h-100">
      <div class="row h-100 align-items-end">
        <div class="col-12">
          <div class="breadcumb--con">
            <h2 class="title">{{ store.name }}</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="breadcrumb-item"><a href="#">업소 세부정보</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ store.name }}</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Contact Area Start ***** -->
  <section class="mona-contact-area section-padding-80-0">
    <div class="container">
      <div class="row align-items-center justify-content-between">

        <!-- Google Maps -->
        <div class="col-12 col-lg-6 col-xl-6">
          <div class="google-maps mb-80">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11956.9355465873!2d24.0768412544878!3d56.9550599906977!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46eecfb0e5073ded%3A0x400cfcd68f2fe30!2z4Kaw4Ka_4KaX4Ka-LCDgprLgp43gpq_gpr7gpp_gp43gpq3gpr_gpoY!5e0!3m2!1sbn!2sbd!4v1543911160102"
              allowfullscreen></iframe>
          </div>
        </div>

        <!-- 업체정보 -->
        <div class="col-12 col-lg-6 col-xl-5">
            <!-- Single Contact Card -->
            <div class="col-12">
            <div class="single-contact-card mb-80">
                <h2>주소/전화번호</h2>
                <h6>{{ store.addr }}<br>
                {{ store.num }} </h6>
            </div>
            </div>

            <!-- Single Contact Card -->
            <div class="col-12">
            <div class="single-contact-card mb-80">
                <h2>영업시간</h2>
                <h6>{{ store.open_hour }} 부터 {{ store.closed_hour }} 까지</h6>
            </div>
            </div>

            <!-- Single Contact Card -->
            <div class="col-12">
            <div class="single-contact-card mb-80">
                <h2>제공서비스</h2>
                <h6>{{ store.service }}</h6>
            </div>
            </div>          
        </div>
      </div>
      <!--업체정보 끝-->

    </div>
  </section>
  <!-- ***** 업체정보 끝 ***** -->

{% endblock  %}

kindeffects/kindeffects/stores/templates/stores/store_mypage.html
{% extends 'base.html' %} 

{% load static %}
{% load qr_code %}
{% load bootstrap4 %}

{% block content %}
<script>
    function onPrint() {      
      const chartDiv = document.querySelector('.chartdiv');
      const footerDiv = document.querySelector('footer');
      //const printContents = document.querySelector('svg').innerHTML;
      const printDiv = document.createElement('DIV');
      //printDiv.className = 'print-div';
      
      document.body.appendChild(printDiv);
      // printDiv.img.src = "{% static 'img/core-img/logo.png' %}";
      chartDiv.style.display = 'none';
      footerDiv.style.display = 'none';
      window.print();

      //chartDiv.style.display = 'block';
      //footerDiv.sytle.display = 'block';
      // printDiv.style.display = 'none';
      //printDiv.innerHTML = '';
    }
</script>


  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area">
    <div class="container h-100">
      <div class="row h-100 align-items-end">
        <div class="col-12">
          <div class="breadcumb--con">
            <h2 class="title">{{ store.name }}</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="breadcrumb-item"><a href="#">업소 세부정보</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ store.name }}</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Contact Area Start ***** -->
  <section class="mona-contact-area section-padding-80-0">
    <div class="container">
      <div class="row align-items-center justify-content-between">

        <!-- QR 다운로드 -->
        <div class="col-12 col-lg-6 col-xl-6 mb-80">
          
            {% qr_from_text store_url size="l" %}
            {% buttons %}   
            
              <button class="btn mona-btn btn-2" onclick="onPrint()">프린트</button>            
                         
            {% endbuttons %}
          
        </div>

        <!-- 업체정보 -->
        <div class="col-12 col-lg-6 col-xl-5">
            <!-- Single Contact Card -->
            <div class="col-12">
            <div class="single-contact-card mb-40">
                <h2>주소/전화번호</h2>
                <h6>{{ store.addr }}<br>
                {{ store.num }} </h6>
            </div>
            </div>

            <!-- Single Contact Card -->
            <div class="col-12">
            <div class="single-contact-card mb-40">
                <h2>영업시간</h2>
                <h6>{{ store.open_hour }} 부터 {{ store.closed_hour }} 까지</h6>
            </div>
            </div>

            <!-- Single Contact Card -->
            <div class="col-12">
            <div class="single-contact-card mb-40">
                <h2>제공서비스</h2>
                <h6>{{ store.service }}</h6>
            </div>
            </div>          
        </div>
      </div>
      <!--업체정보 끝-->

    </div>
  </section>
  <!-- ***** 업체정보 끝 ***** -->

  <!-- 선그래프 불러오기 -->
  <div class="row">
    {% include 'stores/line_graph.html' %}
  </div>
  <!-- 선그래프 끝 -->


{% endblock  %}

kindeffects/kindeffects/stores/templates/stores/store_new.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'stores:store_new' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>save</button>
    </form>
{% endblock %}